field: 53caff22-2ce8-4149-83e4-74b104ad4bb6
fieldLayouts:
  885c5c3e-1437-4e8d-83e4-e7fa7c26a53d:
    tabs:
      -
        fields:
          3ad820fc-2bc8-4eec-a192-6f6bb857c7e0:
            required: false
            sortOrder: 5
          54ae8317-e2b6-4c7c-b7d3-c765bc0e7c85:
            required: false
            sortOrder: 4
          88c93d62-7146-47c4-a618-5c6373e86208:
            required: false
            sortOrder: 2
          734bf298-c9d9-4385-becf-5cea3b2c1e5b:
            required: false
            sortOrder: 6
          aea1eb4c-9c1e-47cf-b001-869cb75aba85:
            required: false
            sortOrder: 3
          dd369345-e0fd-48a8-a9ec-aaa6d7c5d8ba:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  3ad820fc-2bc8-4eec-a192-6f6bb857c7e0:
    contentColumnType: string
    fieldGroup: null
    handle: buttonEntry
    instructions: ''
    name: 'Button Entry'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources: '*'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  54ae8317-e2b6-4c7c-b7d3-c765bc0e7c85:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  88c93d62-7146-47c4-a618-5c6373e86208:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  734bf298-c9d9-4385-becf-5cea3b2c1e5b:
    contentColumnType: text
    fieldGroup: null
    handle: buttonUrl
    instructions: ''
    name: 'Button Url'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aea1eb4c-9c1e-47cf-b001-869cb75aba85:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dd369345-e0fd-48a8-a9ec-aaa6d7c5d8ba:
    contentColumnType: boolean
    fieldGroup: null
    handle: showTree
    instructions: ''
    name: 'Show Tree'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: callout
name: Callout
sortOrder: 3
