field: 53caff22-2ce8-4149-83e4-74b104ad4bb6
fieldLayouts:
  86e8b403-1b1f-4d39-936d-17a2451a4022:
    tabs:
      -
        fields:
          f9ad1539-d926-48ac-a5ed-49d281d531ed: # Rich Text
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  f9ad1539-d926-48ac-a5ed-49d281d531ed: # Rich Text
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: ''
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 7
