field: 53caff22-2ce8-4149-83e4-74b104ad4bb6
fieldLayouts:
  0be4e34e-05eb-47dc-8439-213a5122e571:
    tabs:
      -
        fields:
          5ed32af1-673e-4be3-bd0b-7ff45f08e4fb:
            required: false
            sortOrder: 2
          8bb4c1f0-0870-4430-be62-deec5bd45f2c:
            required: false
            sortOrder: 8
          08d717c8-3d2d-47c4-ba90-69e091596fa4:
            required: false
            sortOrder: 6
          4682f4b1-e94a-4694-ad6f-5dd0f7fcd8c8:
            required: false
            sortOrder: 7
          7861dd6b-590b-4cab-be23-a9cbd1384e2b:
            required: false
            sortOrder: 5
          a627f3be-ac3a-4f1e-92e2-8c0efc307e0b:
            required: false
            sortOrder: 4
          cb0e3dab-78d4-405b-8132-5bef8b778f77:
            required: false
            sortOrder: 3
          f7fd0309-f150-4c01-8a40-40dbac72f0d0:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  5ed32af1-673e-4be3-bd0b-7ff45f08e4fb:
    contentColumnType: string
    fieldGroup: null
    handle: imageAlignment
    instructions: ''
    name: 'Image Alignment'
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - default
              - '1'
            -
              - label
              - Left
            -
              - value
              - left
        -
          __assoc__:
            -
              - default
              - ''
            -
              - label
              - Right
            -
              - value
              - right
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  8bb4c1f0-0870-4430-be62-deec5bd45f2c:
    contentColumnType: text
    fieldGroup: null
    handle: buttonExternalUrl
    instructions: ''
    name: 'Button External URL'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  08d717c8-3d2d-47c4-ba90-69e091596fa4:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4682f4b1-e94a-4694-ad6f-5dd0f7fcd8c8:
    contentColumnType: string
    fieldGroup: null
    handle: buttonEntry
    instructions: ''
    name: 'Button Entry'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources: '*'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7861dd6b-590b-4cab-be23-a9cbd1384e2b:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a627f3be-ac3a-4f1e-92e2-8c0efc307e0b:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cb0e3dab-78d4-405b-8132-5bef8b778f77:
    contentColumnType: text
    fieldGroup: null
    handle: icon
    instructions: 'Icons can be found at https://fontawesome.com/icons'
    name: Icon
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f7fd0309-f150-4c01-8a40-40dbac72f0d0:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:2d5ef627-3d40-4895-8113-2ccae0a01303'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      singleUploadLocationSource: 'volume:dfb05c32-10bd-4f04-99e3-775e23080203'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: '1'
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: zPattern
name: Z-Pattern
sortOrder: 9
