contentColumnType: text
fieldGroup: 8f34b7f7-ccaf-4579-9b50-ed681ffe57ac
handle: blogText
instructions: ''
name: 'Blog Text'
searchable: true
settings:
  availableTransforms:
    - '2'
  availableVolumes:
    - '4'
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
