contentColumnType: text
fieldGroup: ad70e420-b63d-48b6-98a8-053806147750
handle: mapEmbedCode
instructions: ''
name: 'Map Embed Code'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
