contentColumnType: text
fieldGroup: 9c48c40c-7781-4102-8c49-77262f9eba8b
handle: seoDescription
instructions: ''
name: 'SEO Description'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
